export const ROW_HEIGHT = 100;
export const BOX_WIDTH = 208;
export const GAP_WIDTH = BOX_WIDTH / 4;
export const BOX_HEIGHT = ROW_HEIGHT / 2.5;

export const data = [
    {
        period: 'Copper Age',
        years: ['', '', '4000BCE', ''],
    },
    {
        period: 'Bronze Age',
        years: ['3000BCE', '', '2000BCE'],
    },
    {
        period: 'Iron Age',
        years: ['', '1000BCE'],
    },
    {
        period: 'Antiquity',
        years: ['', '1CE'],
    },
    {
        period: 'Middle Ages',
        years: ['', '1000CE'],
    },
    {
        period: 'Modern',
        years: ['', '2000CE', ''],
    },
];

const LEFT = 1.5 * BOX_WIDTH;

export const languages = [
    {
        name: '?',
        x: LEFT + 3 * BOX_WIDTH,
        y: 1 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 1.5 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 3.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Proto-Indo-European',
        x: LEFT + 3 * BOX_WIDTH,
        y: 4 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 4.5 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 10.25 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Proto-Indo-Iranian',
        x: LEFT + 3 * BOX_WIDTH,
        y: 10.75 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 11.25 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 14.35 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Indo-Iranian',
        x: LEFT + 3 * BOX_WIDTH,
        y: 14.85 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 15.35 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 15.85 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Iranian',
        x: LEFT + 3 * BOX_WIDTH,
        y: 16.35 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 16.85 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 17.35 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: '',
        x: LEFT + 3 * BOX_WIDTH,
        y: 18 * BOX_HEIGHT,
        connect: {
            x1: LEFT - GAP_WIDTH,
            y1: 17.35 * BOX_HEIGHT,
            x2: LEFT + 4 * BOX_WIDTH,
            y2: 17.35 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: false,
            left: false,
            right: false,
        },
    },
    {
        name: '',
        x: BOX_WIDTH - GAP_WIDTH,
        y: 17.35 * BOX_HEIGHT,
        connect: {
            x1: 1.25 * BOX_WIDTH,
            y1: 17.325 * BOX_HEIGHT,
            x2: 1.25 * BOX_WIDTH,
            y2: 19.525 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: false,
            left: false,
            right: false,
        },
    },
    {
        name: 'Avestan',
        x: LEFT - 3 * GAP_WIDTH,
        y: 20.1 * BOX_HEIGHT,
        connect: {
            x1: 1.25 * BOX_WIDTH,
            y1: 20.675 * BOX_HEIGHT,
            x2: 1.25 * BOX_WIDTH,
            y2: 25.5 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: '*',
        x: LEFT + 3 * BOX_WIDTH,
        y: 19 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 18.5 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 19 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Median',
        x: LEFT + BOX_WIDTH - 2 * GAP_WIDTH,
        y: 24 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 1 * BOX_WIDTH,
            y1: 24.545 * BOX_HEIGHT,
            x2: LEFT + 1 * BOX_WIDTH,
            y2: 27.75 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Parthian',
        x: LEFT + 2 * BOX_WIDTH - GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 2.25 * BOX_WIDTH,
            y1: 27.05 * BOX_HEIGHT,
            x2: LEFT + 2.25 * BOX_WIDTH,
            y2: 30.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Azari',
        x: LEFT + 2 * BOX_WIDTH + 4 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: LEFT + 3.5 * BOX_WIDTH,
            y2: 26 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Talysh',
        x: LEFT + 2 * BOX_WIDTH + 4 * GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: LEFT + 2.25 * BOX_WIDTH,
            y2: 25 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Caspian',
        x: LEFT + 3.5 * BOX_WIDTH + 5.5 * GAP_WIDTH,
        y: 32.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: '',
        x: LEFT + 3.5 * BOX_WIDTH + 5.5 * GAP_WIDTH,
        y: 33.5 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.5 * BOX_WIDTH + 5 * GAP_WIDTH,
            y1: 33.5 * BOX_HEIGHT,
            x2: LEFT + 6.5 * BOX_WIDTH + 5 * GAP_WIDTH,
            y2: 33.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: false,
            left: false,
            right: false,
        },
    },
    {
        name: 'Gilaki',
        x: LEFT + 3 * BOX_WIDTH + 5 * GAP_WIDTH,
        y: 34.5 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.4 * BOX_WIDTH + 5.5 * GAP_WIDTH,
            y1: 34.5 * BOX_HEIGHT,
            x2: LEFT + 3.4 * BOX_WIDTH + 5.5 * GAP_WIDTH,
            y2: 34.5 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Māzandarāni',
        x: LEFT + 4 * BOX_WIDTH + 6 * GAP_WIDTH,
        y: 34.5 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 4.65 * BOX_WIDTH + 5.5 * GAP_WIDTH,
            y1: 25.5 * BOX_HEIGHT,
            x2: LEFT + 4.65 * BOX_WIDTH + 5.5 * GAP_WIDTH,
            y2: 26 * BOX_HEIGHT,
        },
        nodes: {
            top: true,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Node',
        x: LEFT + 7 * BOX_WIDTH + 6.5 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Kurdish',
        x: LEFT + 7 * BOX_WIDTH + GAP_WIDTH * 1.5,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Kurmanji',
        x: LEFT + 5 * BOX_WIDTH + 7 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Sorani',
        x: LEFT + 6 * BOX_WIDTH + 8 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Node',
        x: LEFT + 9 * BOX_WIDTH + GAP_WIDTH * 3.5,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Zazaki',
        x: LEFT + 7 * BOX_WIDTH + 9 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Gorani',
        x: LEFT + 8 * BOX_WIDTH + 10 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Balochi',
        x: LEFT + 9 * BOX_WIDTH + 11 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Southwestern',
        x: LEFT + 10 * BOX_WIDTH + GAP_WIDTH,
        y: 21 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Old Persian',
        x: LEFT + 15 * BOX_WIDTH + 2 * GAP_WIDTH,
        y: 23 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Middle Persian',
        x: LEFT + 15 * BOX_WIDTH + 2 * GAP_WIDTH,
        y: 25 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Tat',
        x: LEFT + 13 * BOX_WIDTH,
        y: 27 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Juhuri',
        x: LEFT + 13 * BOX_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Luri',
        x: LEFT + 13 * BOX_WIDTH + 5 * GAP_WIDTH,
        y: 27 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'New Persian',
        x: LEFT + 15 * BOX_WIDTH + 7 * GAP_WIDTH,
        y: 27 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Iranian',
        x: LEFT + 14 * BOX_WIDTH + 6 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Dari',
        x: LEFT + 15 * BOX_WIDTH + 7 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Tajik',
        x: LEFT + 16 * BOX_WIDTH + 8 * GAP_WIDTH,
        y: 29 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Bukhāri',
        x: LEFT + 16 * BOX_WIDTH + 8 * GAP_WIDTH,
        y: 31 * BOX_HEIGHT,
        connect: {
            x1: LEFT + 3.75 * BOX_WIDTH,
            y1: 20.5 * BOX_HEIGHT,
            x2: LEFT + 10.5 * BOX_WIDTH,
            y2: 20.5 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Northern',
        x: LEFT + 16 * BOX_WIDTH + 15.5 * GAP_WIDTH,
        y: 20.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Yaghnobi',
        x: LEFT + 16 * BOX_WIDTH + 13 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Ossetian',
        x: LEFT + 17 * BOX_WIDTH + 14 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Node',
        x: LEFT + 19 * BOX_WIDTH + 13.5 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Sanglechi',
        x: LEFT + 18 * BOX_WIDTH + 15 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Ishkashimi',
        x: LEFT + 19 * BOX_WIDTH + 16 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Pamiri',
        x: LEFT + 22 * BOX_WIDTH + 21.5 * GAP_WIDTH,
        y: 20.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Wakhi',
        x: LEFT + 20 * BOX_WIDTH + 17 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Vanji',
        x: LEFT + 21 * BOX_WIDTH + 18 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Yazgulāmi',
        x: LEFT + 22 * BOX_WIDTH + 19 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Shughni',
        x: LEFT + 25 * BOX_WIDTH + 22 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Shughni Proper',
        x: LEFT + 23 * BOX_WIDTH + 20 * GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Oroshori',
        x: LEFT + 24 * BOX_WIDTH + 21 * GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Roshani',
        x: LEFT + 25 * BOX_WIDTH + 22 * GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Khufi',
        x: LEFT + 26 * BOX_WIDTH + 23 * GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Bartangi',
        x: LEFT + 27 * BOX_WIDTH + 24 * GAP_WIDTH,
        y: 26.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Sarikoli',
        x: LEFT + 28 * BOX_WIDTH + 25 * GAP_WIDTH,
        y: 24.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Pashto',
        x: LEFT + 32 * BOX_WIDTH + 24 * GAP_WIDTH,
        y: 20.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Wanetsi',
        x: LEFT + 32 * BOX_WIDTH + 24 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Node',
        x: LEFT + 30 * BOX_WIDTH + 24.5 * GAP_WIDTH,
        y: 20.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Munji',
        x: LEFT + 29 * BOX_WIDTH + 26 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Yidgha',
        x: LEFT + 30 * BOX_WIDTH + 27 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Node',
        x: LEFT + 34 * BOX_WIDTH + 23.5 * GAP_WIDTH,
        y: 20.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Ormori',
        x: LEFT + 33 * BOX_WIDTH + 25 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
    {
        name: 'Parachi',
        x: LEFT + 34 * BOX_WIDTH + 26 * GAP_WIDTH,
        y: 22.5 * BOX_HEIGHT,
        connect: {
            x1: 2.25 * BOX_WIDTH,
            y1: 25 * BOX_HEIGHT,
            x2: 2.25 * BOX_WIDTH,
            y2: 28 * BOX_HEIGHT,
        },
        nodes: {
            top: false,
            bottom: true,
            left: false,
            right: false,
        },
    },
];
